### ISSUE TITLE
前端项目无法启动，求大佬讲解

### ISSUE THREAD

**Issue by QH946** [moshuying/project-3-crm#124]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by QH946** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by moshuying** [comment]
已解决
